### ISSUE TITLE
100 prisoners problem

### ISSUE THREAD

**Issue by wooong1223** [LLLH-2/team-100prisoners#1]
## Description
다음 과정을 거쳐 구현하겠습니다.
## Tasks

- [x]  죄수 상태 생성 및 초기화
- [x]  죄수가 사물함을 열고 자신의 번호를 찾는 동작
- [x] 시행 및 결과 반환
