### ISSUE TITLE
100prisoners problem 구현

### ISSUE THREAD

**Issue by tmttd** [LLLH-2/team-100prisoners#2]
## Description

100명의 죄수 문제 중 서랍장 문제를 구현하려고 함.

## Tasks

1. 죄수 상태 생성 및 초기화

- [x] 랜덤한 번호를 가진 죄수 리스트 생성
- [x] 초기화된 죄수 리스트 반환

2. 죄수가 사물함을 열고 자신의 번호를 찾는 동작

- [x] 각 죄수가 사물함을 열고 번호를 찾는 동작을 수행하는 함수 작성
- [x] 함수는 죄수의 번호와 사물함 상태를 입력으로 받아 죄수가 자신의 번호를 찾았는지 여부를 반환

3. 시행 및 결과 반환

- [x] 주어진 시행 횟수에 대해 각 시행을 수행하고 성공 여부를 카운트하는 함수 작성
- [x] 성공 확률을 계산하여 반환하는 함수 작성
